# static.yml

static_files:
  - source: "assets/images"
    destination: "assets/images"
    include:
      - "*.png"
      - "*.jpg"

  - source: "assets/css"
    destination: "assets/css"
    include:
      - "*.css"

  - source: "assets/js"
    destination: "assets/js"
    include:
      - "*.js"

  - source: "favicon.ico"
    destination: "/"

  - source: "robots.txt"
    destination: "/"

exclude_from_static:
  - "assets/images/tmp"
  - "assets/css/*.map"
  - "assets/js/*.map"

rename_files:
  - from: "assets/images/logo.png"
    to: "assets/images/logo-new.png"

data_files:
  - "data/members.yml"
  - "data/events.yml"
